sudo: false

os:
  - linux
  - windows

language: node_js

node_js:
  - lts/*
  - node

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - yarn global add nyc codecov

script:
  - yarn lint
  - yarn test

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
